### ISSUE TITLE
ReduceTwo not breaking gracefully

### ISSUE THREAD

**Issue by kweis** [jradavenport/spectra#41]
Please add more grace when trying to handle a bias/flat/image list with uneven image sizes. Numpy doesn't care to concatenate differently sized images and fails on line 189 in biascombine:

ERROR: ValueError: all the input array dimensions except for the concatenation axis must match exactly [numpy.lib.shape_base]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/pydis/wrappers.py", line 402, in ReduceTwo
    bias = pydis.biascombine(biaslist, trim=trim)
  File "//anaconda/lib/python2.7/site-packages/pydis/pydis.py", line 189, in biascombine
    all_data = np.dstack( (all_data, im_i) )
  File "//anaconda/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 367, in dstack
    return _nx.concatenate([atleast_3d(_m) for _m in tup], 2)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by kweis** [comment]
I suspect this problem is true for all image reduction so add a warning or error message to all bias/flat reduction sections

**Comment by HeisenbergK** [comment]
Hello, do we have any news on that?
I'm trying to do a bias combine and get the same error

**Comment by jradavenport** [comment]
No work has been done on this, but my understanding is this occurs if the shapes are different between images... what kind of data are you trying to reduce? (where is it from, what shape is it?)
